# Inserts a blank line between shell prompts
add_newline = false

format = """$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$character"""

[directory]
style = "yellow"
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-blue) ($ahead_behind$stashed)](bold 13)"
style = "bold magenta"
conflicted = "═"
untracked = "◼"
modified = "✱"
staged = "✚"
renamed = "➜"
deleted = "✖"
stashed = "*"
ahead = "⬆"
behind = "⬇"
diverged = "⬆⬇"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
